version: '3.8'

services:
  app:
    build: .
    container_name: ml_model_app
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/mlmodels
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: superSecureRandomJWTSecretKey123
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    networks:
      - ml_net

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - ml_net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ml_net

networks:
  ml_net:
    driver: bridge
